/**
 * Syntax Highlighting — Additional Language Definitions
 *
 * Systems/compiled and query language definitions: Rust, Go, SQL.
 * Merged into the main languages record by syntax-languages.ts.
 */

import type { LanguageRules } from './syntax-languages'

// ============================================================================
// Shared Patterns (duplicated to avoid circular imports)
// ============================================================================

const COMMENT_LINE: [RegExp, string] = [/(\/\/.*$|#.*$)/gm, 'syn-comment']
const COMMENT_BLOCK: [RegExp, string] = [/(\/\*[\s\S]*?\*\/)/g, 'syn-comment']
const STRING_DOUBLE: [RegExp, string] = [/("(?:[^"\\]|\\.)*")/g, 'syn-string']
const STRING_SINGLE: [RegExp, string] = [/('(?:[^'\\]|\\.)*')/g, 'syn-string']
const NUMBER: [RegExp, string] = [
  /\b(\d+\.?\d*(?:e[+-]?\d+)?|0x[\da-f]+|0b[01]+|0o[0-7]+)\b/gi,
  'syn-number',
]

// ============================================================================
// Language Definitions
// ============================================================================

export const extraLanguages: Record<string, LanguageRules> = {
  rust: {
    keywords: [
      'as',
      'async',
      'await',
      'break',
      'const',
      'continue',
      'crate',
      'dyn',
      'else',
      'enum',
      'extern',
      'fn',
      'for',
      'if',
      'impl',
      'in',
      'let',
      'loop',
      'match',
      'mod',
      'move',
      'mut',
      'pub',
      'ref',
      'return',
      'self',
      'static',
      'struct',
      'super',
      'trait',
      'type',
      'unsafe',
      'use',
      'where',
      'while',
    ],
    types: [
      'i8',
      'i16',
      'i32',
      'i64',
      'i128',
      'u8',
      'u16',
      'u32',
      'u64',
      'u128',
      'f32',
      'f64',
      'bool',
      'char',
      'str',
      'String',
      'Vec',
      'Option',
      'Result',
      'Box',
      'Rc',
      'Arc',
      'HashMap',
      'HashSet',
      'usize',
      'isize',
    ],
    patterns: [
      { pattern: COMMENT_BLOCK[0], className: COMMENT_BLOCK[1] },
      { pattern: COMMENT_LINE[0], className: COMMENT_LINE[1] },
      { pattern: STRING_DOUBLE[0], className: STRING_DOUBLE[1] },
      { pattern: NUMBER[0], className: NUMBER[1] },
      { pattern: /\b(true|false)\b/g, className: 'syn-number' },
      { pattern: /\b([A-Z]\w*)\b/g, className: 'syn-type' },
      { pattern: /\b(\w+)(?=\s*[!(])/g, className: 'syn-function' },
      { pattern: /(#\[[\w:]+\])/g, className: 'syn-function' },
    ],
  },
  go: {
    keywords: [
      'break',
      'case',
      'chan',
      'const',
      'continue',
      'default',
      'defer',
      'else',
      'fallthrough',
      'for',
      'func',
      'go',
      'goto',
      'if',
      'import',
      'interface',
      'map',
      'package',
      'range',
      'return',
      'select',
      'struct',
      'switch',
      'type',
      'var',
    ],
    types: [
      'int',
      'int8',
      'int16',
      'int32',
      'int64',
      'uint',
      'uint8',
      'uint16',
      'uint32',
      'uint64',
      'float32',
      'float64',
      'complex64',
      'complex128',
      'bool',
      'byte',
      'rune',
      'string',
      'error',
    ],
    patterns: [
      { pattern: COMMENT_BLOCK[0], className: COMMENT_BLOCK[1] },
      { pattern: COMMENT_LINE[0], className: COMMENT_LINE[1] },
      { pattern: STRING_DOUBLE[0], className: STRING_DOUBLE[1] },
      { pattern: /(`[^`]*`)/g, className: 'syn-string' },
      { pattern: NUMBER[0], className: NUMBER[1] },
      { pattern: /\b(true|false|nil|iota)\b/g, className: 'syn-number' },
      { pattern: /\b(\w+)(?=\s*\()/g, className: 'syn-function' },
    ],
  },
  sql: {
    keywords: [
      'select',
      'from',
      'where',
      'and',
      'or',
      'not',
      'in',
      'is',
      'null',
      'like',
      'between',
      'join',
      'inner',
      'left',
      'right',
      'outer',
      'on',
      'as',
      'order',
      'by',
      'group',
      'having',
      'limit',
      'offset',
      'insert',
      'into',
      'values',
      'update',
      'set',
      'delete',
      'create',
      'table',
      'drop',
      'alter',
      'index',
      'primary',
      'key',
      'foreign',
      'references',
      'unique',
      'default',
      'exists',
      'union',
      'all',
      'distinct',
      'count',
      'sum',
      'avg',
      'min',
      'max',
      'case',
      'when',
      'then',
      'else',
      'end',
      'asc',
      'desc',
      'with',
      'recursive',
    ],
    types: [
      'int',
      'integer',
      'varchar',
      'text',
      'boolean',
      'date',
      'timestamp',
      'float',
      'double',
      'decimal',
      'bigint',
      'serial',
      'json',
      'jsonb',
      'uuid',
    ],
    patterns: [
      { pattern: /(--.*$)/gm, className: 'syn-comment' },
      { pattern: COMMENT_BLOCK[0], className: COMMENT_BLOCK[1] },
      { pattern: STRING_SINGLE[0], className: STRING_SINGLE[1] },
      { pattern: STRING_DOUBLE[0], className: STRING_DOUBLE[1] },
      { pattern: NUMBER[0], className: NUMBER[1] },
      { pattern: /\b(true|false|null)\b/gi, className: 'syn-number' },
    ],
  },
}
