if(NOT DEFINED AVA_PLUGIN_RUNNER_SCANNER OR NOT DEFINED AVA_PLUGIN_RUNNER_NEGATIVE_ROOT)
  message(FATAL_ERROR "plugin runner scanner negative self-test requires scanner and scratch paths")
endif()

set(AVA_PLUGIN_RUNNER_NEGATIVE_CASES
  "pipe|pipe(nullptr)"
  "pipe2|pipe2(nullptr, 0)"
  "dup|dup(0)"
  "dup2|dup2(0, 1)")

file(REMOVE_RECURSE "${AVA_PLUGIN_RUNNER_NEGATIVE_ROOT}")
foreach(AVA_PLUGIN_RUNNER_NEGATIVE_CASE IN LISTS AVA_PLUGIN_RUNNER_NEGATIVE_CASES)
  string(REPLACE "|" ";" AVA_PLUGIN_RUNNER_NEGATIVE_FIELDS "${AVA_PLUGIN_RUNNER_NEGATIVE_CASE}")
  list(GET AVA_PLUGIN_RUNNER_NEGATIVE_FIELDS 0 AVA_PLUGIN_RUNNER_NEGATIVE_NAME)
  list(GET AVA_PLUGIN_RUNNER_NEGATIVE_FIELDS 1 AVA_PLUGIN_RUNNER_NEGATIVE_SOURCE)
  set(AVA_PLUGIN_RUNNER_NEGATIVE_DIR "${AVA_PLUGIN_RUNNER_NEGATIVE_ROOT}/${AVA_PLUGIN_RUNNER_NEGATIVE_NAME}")
  file(MAKE_DIRECTORY "${AVA_PLUGIN_RUNNER_NEGATIVE_DIR}")
  file(WRITE "${AVA_PLUGIN_RUNNER_NEGATIVE_DIR}/runner_negative.cpp" "${AVA_PLUGIN_RUNNER_NEGATIVE_SOURCE}\n")
  file(WRITE "${AVA_PLUGIN_RUNNER_NEGATIVE_DIR}/CMakeLists.txt" "# negative scanner fixture\n")
  execute_process(
    COMMAND "${CMAKE_COMMAND}"
      "-DAVA_PLUGIN_RUNNER_DIR=${AVA_PLUGIN_RUNNER_NEGATIVE_DIR}"
      "-DAVA_PLUGIN_CMAKE=${AVA_PLUGIN_RUNNER_NEGATIVE_DIR}/CMakeLists.txt"
      -P "${AVA_PLUGIN_RUNNER_SCANNER}"
    RESULT_VARIABLE AVA_PLUGIN_RUNNER_NEGATIVE_RESULT
    OUTPUT_VARIABLE AVA_PLUGIN_RUNNER_NEGATIVE_STDOUT
    ERROR_VARIABLE AVA_PLUGIN_RUNNER_NEGATIVE_STDERR)
  if(AVA_PLUGIN_RUNNER_NEGATIVE_RESULT EQUAL 0)
    message(FATAL_ERROR "plugin runner scanner failed to reject ${AVA_PLUGIN_RUNNER_NEGATIVE_NAME}")
  endif()
  string(FIND "${AVA_PLUGIN_RUNNER_NEGATIVE_STDOUT}${AVA_PLUGIN_RUNNER_NEGATIVE_STDERR}" "forbidden local process authority" AVA_PLUGIN_RUNNER_REJECTION)
  if(AVA_PLUGIN_RUNNER_REJECTION EQUAL -1)
    message(FATAL_ERROR "plugin runner scanner rejected ${AVA_PLUGIN_RUNNER_NEGATIVE_NAME} for the wrong reason")
  endif()
endforeach()
file(REMOVE_RECURSE "${AVA_PLUGIN_RUNNER_NEGATIVE_ROOT}")
