#pragma once

#include "Paragraph.h"
#include "BasicWindow.h"
#include <list>
#include <optional>

namespace ava::tui::terminal {

class GraphemeSurface;

// class ParagraphPad
//
// Represents an ncurses pad: an off-screen terminal buffer that is not restricted
// by the screen size and that is shown on the screen by refreshing explicit
// rectangles (prefresh).
//
// The content of the pad is a list of Paragraph's. Appending a Paragraph does not
// create or update the underlying ncurses pad; call generate() to (re)create it
// from the current content.
//
class ParagraphPad
{
 private:
  std::vector<std::unique_ptr<Paragraph>> paragraphs_;  // The Paragraph's that make up the content of this pad, in order.
  std::optional<BasicWindow> pad_;                      // The ncurses pad created by the last generate() call, if any.

 private:
  // (Re)generate the GraphemeSurface for this ParagraphPad. Called by generate.
  GraphemeSurface generate_grapheme_surface(columns_t columns);

 public:
  ParagraphPad() = default;

  // Append `paragraph` to the end of the content of this pad.
  void append(std::unique_ptr<Paragraph>&& paragraph)
  {
    paragraphs_.push_back(std::move(paragraph));
  }

  // (Re)generate the ncurses pad from the current content, wrapping every Paragraph to `columns` terminal columns.
  //
  // The ncurses pad is created with `columns` terminal columns and a height that fits all wrapped rows,
  // with a single blank row between consecutive Paragraph's iff `blank_line_between_block_rows` is true.
  // A pad generated by an earlier call, if any, is destroyed. Every TextSpan is written with its own rendition,
  // falling back to the default rendition of the Paragraph that it belongs to. The terminal must have been
  // initialized (Context) before calling this function.
  void generate(columns_t columns, bool blank_line_between_block_rows = true);

  // Calls pad_.prefresh.
  void prefresh(Position pad_pos, Position screen_pos, Dimension screen_size);

  // Accessor.
  std::vector<std::unique_ptr<Paragraph>> const& paragraphs() const { return paragraphs_; }

  // Return the dimensions of the generated ncurses pad.
  Dimension dimension() const;

  // Access the ncurses pad BasicWindow underlying this pad; for example for input functions that
  // must not implicitly refresh stdscr over the pad (see BasicWindow::get_wch).
  BasicWindow& basic_window();

  AVA_DEBUG_PRINT_MEMBERS_ON
};

} // namespace ava::tui::terminal
