#! /bin/bash
# generate_ctags_json.sh -- produce the JSON tags file used for debug printer
# generation (goal 03).
#
# Runs list_ava_sources.sh (goal 02) to enumerate the ava library source files
# and pipes that list into ctags in JSON output mode, writing the result to the
# output path passed as $1. The ctags executable to use is passed as $2; it was
# located and JSON-capability-checked by CMake at configure time, so this script
# assumes a JSON-capable Universal Ctags.
#
# On success the exact sorted source input list is recorded beside the JSON
# output as <output-json-path>.sources (for example tags.json.sources), with a
# deterministic CMake-format SHA-256 manifest at <output-json-path>.sources.sha256.
# Configure time uses those manifests to detect added/deleted and edited sources
# without relying on mtimes. Both manifests are staged and published only after
# ctags succeeds, so a broken run never replaces either previous good manifest.
#
# This is the implementation behind the manual `ctags-json` pseudo-target and is
# also invoked from configure-time / generate-print-members refresh paths. ctags
# runs with the repository root as its working directory, so the recorded paths
# are repo-root-relative.
#
# SHA-256 lines are generated by the CMake executable supplied by the caller,
# avoiding a separate host-tool dependency. The caller also supplies flock and
# the shared per-build-tree lock used by every tags/printer writer.
#
# Usage: generate_ctags_json.sh <output-json-path> <ctags-executable> \
#          <cmake-executable> <flock-executable> <generation-lock>
set -euo pipefail

lock_held=false
if [[ "${1:-}" == "--ava-generation-lock-held" ]]; then
  lock_held=true
  shift
fi

if [[ $# -ne 5 ]]; then
  echo "usage: $0 <output-json-path> <ctags-executable> <cmake-executable> <flock-executable> <generation-lock>" >&2
  exit 2
fi

out="$1"
ctags_exe="$2"
cmake_exe="$3"
flock_exe="$4"
generation_lock="$5"

# Resolve caller-relative paths before ctags changes to the repository root.
if [[ "$out" != /* ]]; then
  out="$(pwd -P)/$out"
fi
if [[ "$generation_lock" != /* ]]; then
  generation_lock="$(pwd -P)/$generation_lock"
fi

# flock's --close keeps the held descriptor out of ctags and any subprocesses.
# Re-exec under the lock so it covers staging and the complete publication
# transaction, while concurrent printer readers use the exact same lock.
if [[ "$lock_held" == false ]]; then
  mkdir -p -- "$(dirname -- "$generation_lock")"
  exec "$flock_exe" --exclusive --close "$generation_lock" \
    "$0" --ava-generation-lock-held \
    "$out" "$ctags_exe" "$cmake_exe" "$flock_exe" "$generation_lock"
fi

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd -- "$script_dir/../.." && pwd)

# The absolute out keeps staged manifest paths and the final tags path stable
# after the script cds to the repository root for deterministic path recording.
sources_out="${out}.sources"
sources_sha256_out="${sources_out}.sha256"
sources_tmp="${sources_out}.tmp.$$"
sources_sha256_tmp="${sources_sha256_out}.tmp.$$"

cleanup() {
  rm -f -- "$sources_tmp" "$sources_sha256_tmp"
}
trap cleanup EXIT

# Create the output directory before ctags tries to write into it.
mkdir -p "$(dirname -- "$out")"

# Stage the exact sorted source list that will be fed to ctags.
"$script_dir"/list_ava_sources.sh >"$sources_tmp"

# Run from the repository root so each CMake sha256sum line has the deterministic
# "<hash>  <repo-relative-path>" format also computed at configure time.
cd "$repo_root"
while IFS= read -r source_path; do
  "$cmake_exe" -E sha256sum "$source_path"
done <"$sources_tmp" >"$sources_sha256_tmp"

# ctags refuses to overwrite a file that does not look like a tags file; a
# previously generated JSON tags.json is not a Vi tag file, so remove any stale
# output first to let ctags write it fresh.
rm -f -- "$out"

# -L file read the list of input files from the staged source list.
# -f out  write the JSON tags to the requested path.
# -D ...  expand the opt-in/out macros to a print_members definition so that the
#         generator can tell which classes/structs opted in straight from the
#         tags file (a type declares print_members_opt_in/out iff it has the macro).
"$ctags_exe" \
  --output-format=json \
  --language-force=C++ \
  --fields=+KinSz \
  --kinds-C++=+p \
  -D 'AVA_DEBUG_PRINT_MEMBERS_ON=void print_members_opt_in() { }' \
  -D 'AVA_DEBUG_PRINT_MEMBERS_ON_BASE(base_class)=void print_members_opt_in() { }' \
  -D 'AVA_DEBUG_PRINT_MEMBERS_OPT_OUT=void print_members_opt_out() { }' \
  -D 'AVA_DEBUG_PURE_VIRTUAL_PRINT_MEMBERS=void print_members_opt_out() { }' \
  -D 'AVA_PRINT_ON_MEMBERS=void print_members_opt_out() { }' \
  -L "$sources_tmp" -f "$out"

# ctags succeeded: publish both staged manifests. The path manifest is moved
# last and acts as the commit marker for the matching signature manifest.
mv -f -- "$sources_sha256_tmp" "$sources_sha256_out"
mv -f -- "$sources_tmp" "$sources_out"
trap - EXIT
