#pragma once

#include <boost/intrusive_ptr.hpp>
#include <concepts>
#include <cstring>
#include <functional>
#include <iostream>
#include <memory>
#include <mutex>
#include <type_traits>

// Do NOT include "debug.h" here.

#ifdef CWDS_DEBUG_OSTREAM_OPERATORS_H
// The reason that this error should never happen is because ava/debug/debug_ostream_operators.h should
// ONLY be included by the generated print_members.cpp files, generated by cmake/scripts/generate_print_members.py
// which includes this header immediately after sys.h.
#error "ava/debug/debug_ostream_operators.h must be included before cwds/debug_ostream_operators.h is."
#endif

namespace debug {
// Allow using `os << __write__("member:")` in the generated `print_members`
// member functions to avoid getting quotes around those string literals.
struct AvaRawDebugString { char const* ptr; };
[[gnu::always_inline]] inline AvaRawDebugString __write__(char const* ptr) { return {ptr}; }
[[gnu::always_inline]] inline std::ostream& operator<<(std::ostream& os, AvaRawDebugString raw_str)
{
  os.write(raw_str.ptr, std::strlen(raw_str.ptr));
  return os;
}
} // namespace debug

namespace debug::ostream_operators {

inline std::ostream& operator<<(std::ostream& os, std::mutex const& UNUSED_ARG(mutex))
{
  os.write("$mutex$", 7);
  return os;
}

template<typename T>
inline std::ostream& operator<<(std::ostream& os, std::function<T> const& UNUSED_ARG(func))
{
  os.write("$std::function$", 15);
  return os;
}

template<typename T>
concept ConceptHasToString = requires(T t)
{
  { to_string(t) } -> std::convertible_to<std::string>;
};

template<typename T>
concept ConceptIsEnum = std::is_enum_v<T>;

template<ConceptIsEnum T>
inline std::ostream& operator<<(std::ostream& os, T const& e);

template<typename T>
concept ConceptIsNonIntrusiveNonArrayPointer =
    std::same_as<std::remove_cv_t<std::remove_pointer_t<T>>, std::unique_ptr<T>> ||
    std::same_as<std::remove_cv_t<std::remove_pointer_t<T>>, std::shared_ptr<T>> ||
    std::is_pointer_v<T>;

template<ConceptIsNonIntrusiveNonArrayPointer T>
inline std::ostream& operator<<(std::ostream& os, T const& obj);

// boost::intrusive_ptr defines its own operator<< as
// template<class E, class T, class Y> std::basic_ostream<E, T> & operator<< (std::basic_ostream<E, T> & os, intrusive_ptr<Y> const & p)
// In order to override that we use a constrained template to win over the unconstrained one:
template<class E, class T, class Y>
requires (sizeof(E) <= sizeof(char32_t)) // Expected to be always true, but it counts as a constrain.
inline std::basic_ostream<E, T>& operator<<(std::basic_ostream<E, T>& os, boost::intrusive_ptr<Y> const& p);

template<typename T>
inline std::ostream& operator<<(std::ostream& os, std::shared_ptr<T> const& ptr);

inline std::ostream& operator<<(std::ostream& os, std::string const& str)
{
  // Put double quotes around strings.
  os << '"';
  os.write(str.data(), str.size());
  os << '"';
  return os;
}

inline std::ostream& operator<<(std::ostream& os, char const* str);

} // namespace debug::ostream_operators

// Include all operator<<'s before defining ones that use LIBCWD_USING_OSTREAM_PRELUDE.
#include <cwds/debug_ostream_operators.h>
#include "utils/print_pointer.h"
#include "utils/to_string.h"

namespace debug::ostream_operators {

template<ConceptIsNonIntrusiveNonArrayPointer T>
std::ostream& operator<<(std::ostream& os, T const& obj)
{
  utils::operator<<(os, utils::print_pointer(obj));
  return os;
}

// boost::intrusive_ptr defines its own operator<< as
// template<class E, class T, class Y> std::basic_ostream<E, T> & operator<< (std::basic_ostream<E, T> & os, intrusive_ptr<Y> const & p)
// In order to override that we use a constrained template to win over the unconstrained one:
template<class E, class T, class Y>
requires (sizeof(E) <= sizeof(char32_t)) // Expected to be always true, but it counts as a constrain.
std::basic_ostream<E, T>& operator<<(std::basic_ostream<E, T>& os, boost::intrusive_ptr<Y> const& p)
{
  utils::operator<< <Y>(os, utils::print_pointer(p));
  return os;
}

template<ConceptIsEnum T>
std::ostream& operator<<(std::ostream& os, T const& e)
{
  if constexpr (ConceptHasToString<T>)
  {
    std::string str(to_string(e));
    os.write(str.data(), str.size());
  }
  else
  {
    std::string str(utils::to_string(e));
    os.write(str.data(), str.size());
  }
  return os;
}

std::ostream& operator<<(std::ostream& os, char const* str)
{
  os << debug::print_string(str);
  return os;
}

template<typename T>
std::ostream& operator<<(std::ostream& os, std::optional<T> const& opt)
{
  if (opt.has_value())
  {
    // There is no need to write std::boolalpha here because we can only get here if LIBCWD_USING_OSTREAM_PRELUDE
    // was already used, in which case that should already have been taken care of.
    LIBCWD_USING_OSTREAM_PRELUDE;
    os << opt.value();
  }
  else
    os.write("$no_value$", 10);
  return os;
}

template<typename T>
std::ostream& operator<<(std::ostream& os, std::shared_ptr<T> const& ptr)
{
  return os << utils::print_pointer(ptr);
}

} // namespace debug::ostream_operators
