#pragma once

#include <threadsafe/threadsafe.h>
#include <boost/intrusive_ptr.hpp>
#include <concepts>
#include <condition_variable>
#include <cstring>
#include <functional>
#include <iostream>
#include <memory>
#include <mutex>
#include <optional>
#include <type_traits>
#include <variant>
#include "NAMESPACE_DEBUG.h"

// Do NOT include "debug.h" here.

#ifdef CWDS_DEBUG_OSTREAM_OPERATORS_H
// The reason that this error should never happen is because ava/debug/debug_ostream_operators.h should
// ONLY be included by the generated print_members.cpp files, generated by cmake/scripts/generate_print_members.py
// which includes this header immediately after sys.h.
#error "ava/debug/debug_ostream_operators.h must be included before cwds/debug_ostream_operators.h is."
#endif

NAMESPACE_DEBUG_START

// Allow using `os << __write__("member:")` in the generated `print_members`
// member functions to avoid getting quotes around those string literals.
struct AvaRawDebugString { char const* ptr; };
[[gnu::always_inline]] inline AvaRawDebugString __write__(char const* ptr) { return {ptr}; }
[[gnu::always_inline]] inline std::ostream& operator<<(std::ostream& os, AvaRawDebugString raw_str)
{
  os.write(raw_str.ptr, std::strlen(raw_str.ptr));
  return os;
}

NAMESPACE_DEBUG_END

struct termios;

namespace debug::ostream_operators {

//=============================================================================
// Helper types.
//
namespace detail {

template<typename T>
struct is_std_function : std::false_type { };

template<typename Signature>
struct is_std_function<std::function<Signature>> : std::true_type { };

template<typename T>
using pointee_t = std::remove_cv_t<std::remove_pointer_t<T>>;

} // namespace detail

//=============================================================================
// Concepts.
//
template<typename T>
concept ConceptAnyStdFunction = detail::is_std_function<std::remove_cvref_t<T>>::value;

template<typename T>
concept ConceptCharacterPointer =
    std::is_pointer_v<T> &&
    (std::same_as<detail::pointee_t<T>, char>          ||
     std::same_as<detail::pointee_t<T>, signed char>   ||
     std::same_as<detail::pointee_t<T>, unsigned char> ||
     std::same_as<detail::pointee_t<T>, wchar_t>       ||
     std::same_as<detail::pointee_t<T>, char8_t>       ||
     std::same_as<detail::pointee_t<T>, char16_t>      ||
     std::same_as<detail::pointee_t<T>, char32_t>);

template<typename T>
concept ConceptHasToString = requires(T t)
{
  { to_string(t) } -> std::convertible_to<std::string>;
};

template<typename T>
concept ConceptIsEnum = std::is_enum_v<T>;

template<typename T>
concept ConceptIsNonIntrusiveNonArrayNonCharPointer =
  (std::same_as<detail::pointee_t<T>, std::unique_ptr<T>> ||
   std::same_as<detail::pointee_t<T>, std::shared_ptr<T>> ||
   std::is_pointer_v<T>) && !ConceptCharacterPointer<T>;

//=============================================================================
// Forward declarations
//

inline std::ostream& operator<<(std::ostream& os, std::same_as<std::mutex> auto const& mx);
inline std::ostream& operator<<(std::ostream& os, std::same_as<std::condition_variable> auto const& cv);
inline std::ostream& operator<<(std::ostream& os, std::same_as<std::istream> auto const& in);
inline std::ostream& operator<<(std::ostream& os, std::same_as<std::ostream> auto const& out);

template<typename T>
inline std::ostream& operator<<(std::ostream& os, std::reference_wrapper<T> const& ref);

template<typename... Args>
inline std::ostream& operator<<(std::ostream& os, std::variant<Args...> const& var);

//-----------------
// Pointer types
template<ConceptIsNonIntrusiveNonArrayNonCharPointer T>
inline std::ostream& operator<<(std::ostream& os, T const& ptr);

// boost::intrusive_ptr defines its own operator<< as
// template<class E, class T, class Y> std::basic_ostream<E, T> & operator<< (std::basic_ostream<E, T> & os, intrusive_ptr<Y> const & p)
// In order to override that we use a constrained template to win over the unconstrained one:
template<class E, class T, class Y>
requires (sizeof(E) <= sizeof(char32_t)) // Expected to be always true, but it counts as a constrain.
inline std::basic_ostream<E, T>& operator<<(std::basic_ostream<E, T>& os, boost::intrusive_ptr<Y> const& p);

template<typename T>
inline std::ostream& operator<<(std::ostream& os, std::shared_ptr<T> const& ptr);

template<ConceptAnyStdFunction T>
inline std::ostream& operator<<(std::ostream& os, T const& fn);

inline std::ostream& operator<<(std::ostream& os, char const* str);
//-----------------

// Non-inline, defined below.
template<ConceptIsEnum T>
std::ostream& operator<<(std::ostream& os, T const& e);

// Non-inline, defined below.
template<typename T>
std::ostream& operator<<(std::ostream& os, std::optional<T> const& opt);

// Non-inline, defined in maxlen.cpp.
std::ostream& operator<<(std::ostream& os, std::string const& str);

// Non-inline, defined in debug_ostream_operators.cpp.
std::ostream& operator<<(std::ostream& os, struct termios const& te);

//=============================================================================

} // namespace debug::ostream_operators

// Include all operator<<'s before defining ones that use LIBCWD_USING_OSTREAM_PRELUDE.
#include <cwds/debug_ostream_operators.h>
#include "print_reference.h"
#include "utils/print_pointer.h"
#include "utils/to_string.h"

namespace debug::ostream_operators {

//=============================================================================
// Implementation of operator<<'s marked as inline.
//

std::ostream& operator<<(std::ostream& os, std::same_as<std::mutex> auto const& UNUSED_ARG(mx))
{
  os.write("$mutex$", 7);
  return os;
}

std::ostream& operator<<(std::ostream& os, std::same_as<std::condition_variable> auto const& UNUSED_ARG(cv))
{
  os.write("$condition_variable$", 20);
  return os;
}

std::ostream& operator<<(std::ostream& os, std::same_as<std::istream> auto const& in)
{
  return os << ::ava_utils::print_reference(in);
}

std::ostream& operator<<(std::ostream& os, std::same_as<std::ostream> auto const& out)
{
  return os << ::ava_utils::print_reference(out);
}

template<typename T>
std::ostream& operator<<(std::ostream& os, std::reference_wrapper<T> const& ref)
{
  return os << ::ava_utils::print_reference(ref);
}

template<typename T, typename POLICY_MUTEX>
std::ostream& operator<<(std::ostream& os, threadsafe::Unlocked<T, POLICY_MUTEX> const& unlocked)
{
  return os << "threadsafe::Unlocked<" << NAMESPACE_DEBUG::type_name_of<T>() << ">@" << (void const*)&unlocked;
}

template<typename... Args>
std::ostream& operator<<(std::ostream& os, std::variant<Args...> const& UNUSED_ARG(var))
{
  os.write("$variant$", 9);
  return os;
}

template<ConceptIsNonIntrusiveNonArrayNonCharPointer T>
std::ostream& operator<<(std::ostream& os, T const& ptr)
{
  ::utils::operator<<(os, ::utils::print_pointer(ptr));
  return os;
}

template<class E, class T, class Y>
requires (sizeof(E) <= sizeof(char32_t))
std::basic_ostream<E, T>& operator<<(std::basic_ostream<E, T>& os, boost::intrusive_ptr<Y> const& p)
{
  ::utils::operator<< <Y>(os, ::utils::print_pointer(p));
  return os;
}

template<typename T>
std::ostream& operator<<(std::ostream& os, std::shared_ptr<T> const& ptr)
{
  return os << ::utils::print_pointer(ptr);
}

template<ConceptAnyStdFunction T>
std::ostream& operator<<(std::ostream& os, T const& UNUSED_ARG(fn))
{
  os.write("$std::function$", 15);
  return os;
}

std::ostream& operator<<(std::ostream& os, char const* str)
{
  os << ::debug::print_string(str);
  return os;
}

//=============================================================================
// Implementation of operator<<'s that are not marked as inline.
//

template<ConceptIsEnum T>
std::ostream& operator<<(std::ostream& os, T const& e)
{
  if constexpr (ConceptHasToString<T>)
  {
    std::string str(to_string(e));
    os.write(str.data(), str.size());
  }
  else
  {
    std::string str(utils::to_string(e));
    os.write(str.data(), str.size());
  }
  return os;
}

template<typename T>
std::ostream& operator<<(std::ostream& os, std::optional<T> const& opt)
{
  if (opt.has_value())
  {
    // There is no need to write std::boolalpha here because we can only get here if LIBCWD_USING_OSTREAM_PRELUDE
    // was already used, in which case that should already have been taken care of.
    LIBCWD_USING_OSTREAM_PRELUDE;
    os << opt.value();
  }
  else
    os.write("$no_value$", 10);
  return os;
}

//=============================================================================

} // namespace debug::ostream_operators
