function toPascalCase(value: string): string {
  return value
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

export function createReadme(pluginName: string, safeName: string): string {
  return `# ${pluginName}\n\nGenerated by \`ava plugin init\`.\n\n## Development\n\n\`\`\`bash\npnpm install\npnpm run build\n\`\`\`\n\n## Plugin metadata\n\n- ID: \`${safeName}\`\n- Package: \`@ava-plugin/${safeName}\`\n\n## Notes\n\nSee \`docs/plugins/PLUGIN_TEMPLATE.md\` in the AVA repository for full plugin guidelines.`
}

export function createPluginSource(pluginName: string, safeName: string): string {
  const typeName = `${toPascalCase(safeName)}Plugin`
  const contextName = `${toPascalCase(safeName)}PluginContext`

  return `export interface ${contextName} {\n  cwd: string\n}\n\nexport interface ${typeName} {\n  id: '${safeName}'\n  name: '${pluginName}'\n  activate: (context: ${contextName}) => Promise<void>\n}\n\nexport const plugin: ${typeName} = {\n  id: '${safeName}',\n  name: '${pluginName}',\n  activate: async (context) => {\n    console.log('[${safeName}] activated in', context.cwd)\n  },\n}\n`
}
