export function createReadme(pluginName: string, safeName: string): string {
  return `# ${pluginName}

AVA extension plugin generated by \`ava plugin init\`.

## Development

\`\`\`bash
pnpm install
pnpm run build
pnpm run test
\`\`\`

## Plugin metadata

- ID: \`${safeName}\`
- Package: \`@ava-plugin/${safeName}\`

## Structure

- \`ava-extension.json\` — Plugin manifest
- \`src/index.ts\` — Entry point (activate/deactivate)
- \`src/index.test.ts\` — Tests

## Docs

See \`docs/plugins/PLUGIN_SDK.md\` in the AVA repository for full plugin development guide.`
}

export function createPluginSource(pluginName: string, safeName: string): string {
  return `import type { Disposable, ExtensionAPI } from '@ava/core-v2/extensions'

export function activate(api: ExtensionAPI): Disposable {
  api.log.info('${safeName} activated')

  // Register tools, commands, middleware, etc. here:
  // api.registerTool(myTool)
  // api.registerCommand(myCommand)

  return {
    dispose() {
      api.log.info('${safeName} deactivated')
    },
  }
}
`
}

export function createManifest(pluginName: string, safeName: string): string {
  return JSON.stringify(
    {
      name: safeName,
      version: '0.1.0',
      description: `${pluginName} — AVA extension plugin`,
      main: 'dist/index.js',
      capabilities: [],
    },
    null,
    2
  )
}

export function createPluginTest(_pluginName: string, safeName: string): string {
  return `import { describe, expect, it } from 'vitest'
import { createMockExtensionAPI } from '@ava/core-v2/__test-utils__/mock-extension-api'
import { activate } from './index.js'

describe('${safeName}', () => {
  it('activates successfully', () => {
    const { api } = createMockExtensionAPI()
    const disposable = activate(api)
    expect(disposable).toBeDefined()
    expect(disposable.dispose).toBeTypeOf('function')
  })

  it('logs activation message', () => {
    const { api } = createMockExtensionAPI()
    activate(api)
    expect(api.log.info).toHaveBeenCalledWith('${safeName} activated')
  })

  it('cleans up on dispose', () => {
    const { api } = createMockExtensionAPI()
    const disposable = activate(api)
    disposable.dispose()
    expect(api.log.info).toHaveBeenCalledWith('${safeName} deactivated')
  })
})
`
}
