/**
 * Praxis Agent Presets
 * The 14 built-in Praxis agents with tier-based delegation.
 */

import {
  Bug,
  Building,
  Code,
  Compass,
  Crown,
  Eye,
  Layers,
  Layout,
  ListTodo,
  Rocket,
  Search,
  Server,
  Shield,
  TestTube,
} from 'lucide-solid'
import type { AgentPreset, IconComponent } from './agent-defaults'

export const praxisAgentPresets: AgentPreset[] = [
  // Commander
  {
    id: 'commander',
    name: 'Commander',
    description: 'Plans and coordinates the team — never writes code directly',
    icon: Crown as IconComponent,
    enabled: true,
    tier: 'commander',
    tools: ['question', 'attempt_completion'],
    delegates: [
      'frontend-lead',
      'backend-lead',
      'qa-lead',
      'fullstack-lead',
      'planner',
      'architect',
    ],
    domain: 'fullstack',
    capabilities: ['coordination', 'planning', 'delegation'],
  },
  // Leads
  {
    id: 'frontend-lead',
    name: 'Frontend Lead',
    description: 'Manages frontend development',
    icon: Layout as IconComponent,
    enabled: true,
    tier: 'lead',
    delegates: ['coder', 'tester'],
    domain: 'frontend',
    capabilities: ['frontend-management', 'delegation'],
  },
  {
    id: 'backend-lead',
    name: 'Backend Lead',
    description: 'Manages backend development',
    icon: Server as IconComponent,
    enabled: true,
    tier: 'lead',
    delegates: ['coder', 'tester', 'debugger'],
    domain: 'backend',
    capabilities: ['backend-management', 'delegation'],
  },
  {
    id: 'qa-lead',
    name: 'QA Lead',
    description: 'Manages testing and review',
    icon: Shield as IconComponent,
    enabled: true,
    tier: 'lead',
    delegates: ['tester', 'reviewer'],
    domain: 'testing',
    capabilities: ['qa-management', 'delegation'],
  },
  {
    id: 'fullstack-lead',
    name: 'Fullstack Lead',
    description: 'Manages cross-cutting work',
    icon: Layers as IconComponent,
    enabled: true,
    tier: 'lead',
    delegates: ['coder', 'tester', 'debugger', 'reviewer', 'devops'],
    domain: 'fullstack',
    capabilities: ['fullstack-management', 'delegation'],
  },
  // Workers
  {
    id: 'coder',
    name: 'Coder',
    description: 'Writes and modifies code files',
    icon: Code as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['read_file', 'write_file', 'create_file', 'delete_file', 'edit', 'grep', 'glob'],
    domain: 'fullstack',
    capabilities: ['code-generation', 'refactoring'],
  },
  {
    id: 'tester',
    name: 'Tester',
    description: 'Writes and runs tests',
    icon: TestTube as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['read_file', 'write_file', 'create_file', 'bash', 'grep', 'glob'],
    domain: 'testing',
    capabilities: ['test-writing', 'test-running'],
  },
  {
    id: 'reviewer',
    name: 'Reviewer',
    description: 'Reviews code for quality, bugs, and security',
    icon: Eye as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['read_file', 'grep', 'glob'],
    domain: 'fullstack',
    capabilities: ['code-review', 'security-analysis'],
  },
  {
    id: 'researcher',
    name: 'Researcher',
    description: 'Explores the codebase and gathers context',
    icon: Search as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['read_file', 'grep', 'glob', 'ls'],
    domain: 'fullstack',
    capabilities: ['codebase-exploration', 'context-gathering'],
  },
  {
    id: 'debugger',
    name: 'Debugger',
    description: 'Debugs and fixes errors',
    icon: Bug as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['read_file', 'write_file', 'edit', 'bash', 'grep', 'glob'],
    domain: 'fullstack',
    capabilities: ['debugging', 'error-diagnosis'],
  },
  {
    id: 'architect',
    name: 'Architect',
    description: 'Reviews architecture and suggests patterns',
    icon: Building as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['read_file', 'grep', 'glob', 'ls', 'question'],
    domain: 'fullstack',
    capabilities: ['architecture-review', 'pattern-suggestion'],
  },
  {
    id: 'planner',
    name: 'Planner',
    description: 'Breaks complex tasks into subtasks',
    icon: ListTodo as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['read_file', 'grep', 'glob', 'ls'],
    domain: 'fullstack',
    capabilities: ['task-planning', 'decomposition'],
  },
  {
    id: 'devops',
    name: 'DevOps',
    description: 'Runs shell commands and manages build/deploy',
    icon: Rocket as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['bash', 'read_file', 'glob', 'grep'],
    domain: 'devops',
    capabilities: ['shell-commands', 'build-management'],
  },
  {
    id: 'explorer',
    name: 'Explorer',
    description: 'Read-only codebase exploration and analysis',
    icon: Compass as IconComponent,
    enabled: true,
    tier: 'worker',
    tools: ['read_file', 'glob', 'grep', 'ls', 'websearch', 'webfetch'],
    domain: 'fullstack',
    capabilities: ['codebase-exploration', 'analysis'],
  },
]
